### ISSUE TITLE
[BUG] key binds work with just the modifiers pressed

### ISSUE THREAD

**Issue by sooheon** [alixlahuec/zotero-roam#21] opened 2022-02-17 07:18 UTC
relevant to #1 

Had the same issue, default bind wasn't working.

I think it's good to use a library to handle these things -- in addition to alt keybindings not working, I tried rebinding like `{'p': true, 'metaKey': true, 'ctrlKey': true}`, and this is behaving strangely. Just pressing the two modifier keys together will pop up the search panel. Maybe you didn't consider double modifiers in your code?

**Comment by sooheon** [comment] 2022-02-17 07:22
This also happens when binding `{';': true, 'metaKey': true}` -- when I press CMD (metaKey) to give other key binds, this will intercept and pop up the search bar.

**Comment by greenmeen** [comment] 2022-02-17 23:08
There seems to be an occasional issue with modifiers registration - I had done some checking before but couldn't reproduce or pin down the cause.
Unfortunately I don't currently have time to revisit this specific bug since it will be fixed in the next major release, which is almost ready (hoping to publish in the next few weeks). The codebase is migrating to React, so shortcuts will be handled by Blueprint's hotkeys implementation. It'll be much more reliable than the hacky system currently in place, and  writing key combinations will also be a lot more natural (e.g "alt+c").

**Comment by sooheon** [comment] 2022-02-18 09:59
I could beta test the new release if you'd like -- I can't find a key combination that works currently.

**Comment by alixlahuec** [comment] 2022-10-04 15:44
@sooheon Upcoming release will leverage Blueprint's hotkeys (which is what Roam uses), so it should clear up any issues with the extension's custom handlers. Submitting it for review by the Roam team today, will make an announcement when it's available!

**Closed by alixlahuec** 2022-10-04 15:44 UTC
Labels: bug
